# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('urlLink', models.URLField()),
                ('emailLink', models.EmailField(max_length=254)),
            ],
        ),
    ]
